### ISSUE TITLE
reset 스타일으로 인해 table 태그 align, cellpadding 속성값이 무시

### ISSUE THREAD

**Issue by mkki** [mkki/study-note#23]
### 이슈 내용

table 관련 태그 reset css 영향으로 `align`과 `cellpadding` 적용 안됨

### 해결 방법

1. reset css 유지

 - [revert-layer](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer)

```scss
.element {
    table {
        padding: revert-layer;
        margin: revert-layer;

        th,
        td {
            padding: revert-layer;
            margin: revert-layer;
        }
    }
}
```

2. reset css 삭제

- 개별 table 요소 마다 스타일 추가해줘야함

### reset-layer 관련

- 자기 보다 우선 순위가 낮은 cascade layers(`@layer`)에 적용된 스타일 적용
- `@layer`에 정의되지 않은 스타일은 **unlayered style**라고 함
-  **unlayered style**에서는 **정의된 스타일이 없으면** 기본 브라우저 스타일이 적용
  - `cellpadding`과 같이 테이블에서 특수하게 계산되어지는 스타일시트는 브라우저에서 별도 레이어로 분리해놓는 것 같음. 그래서 브라우저 기본 스타일이 아니라 해당 레이어 내 스타일이 적용되면서 무시되던 값이 유지되는 것
  - revert는 무조건 브라우저 기본스타일 적용이라 위 스타일시트 무시하는 것 같음.

```scss
button {
  color: black;
}

@layer foo {
  button {
    color: blue;
  }
}

@layer bar {
  button {
    color: red;
  }

  button.revert-color {
    color: revert-layer;  // blue 적용
  }
}
```
